
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const REGISTRADO = 'REGISTRADO';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const USUARIO_EDITADO = 'USUARIO_EDITADO';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const ERROR_USUARIO = 'ERROR_USUARIO';
